### ISSUE TITLE
Cloning and building instructions for windows

### ISSUE THREAD

**Issue by david-sackstein** [ShiftMediaProject/FFmpeg#23]
My objective is to build ffmpeg within Visual Studio 2015.
I am assuming that the first thing I need to do is to run the project_get_dependencies.bat  in the ffmpeg folder, but fails fails to clone the projects.
Running the clone command for all of the projects manually succeeds and they are now next to ffmpeg under my project root.
There are now two problems that are described below.
## Context
It is not clear how to acquire all the prerequisites.

## Expected Behavior
After following instructions in the project, ffmpeg.sln should build all the components of ffmpeg.

## Actual Behavior
**1. yasm succeeds to compile some asm files but fails on others. Sample output:**

1>  Assembling cpuid.asm
1>  Assembling emms.asm
1>  Assembling fixed_dsp.asm
1>  Assembling float_dsp.asm
1>  Assembling imgutils.asm
1>  Assembling lls.asm
1>  Assembling pixelutils.asm
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomizations\yasm.targets(45,5): error MSB3721: The command ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\"vsyasm.exe -Xvc -f x64 -i ".. .. ShiftMedia\FFmpeg\SMP\\" -i ".. .. \ShiftMedia\FFmpeg\SMP\\..\\" -o ".. ..\ShiftMedia\FFmpeg\SMP\obj\Debug\x64\libavutil\\" -rnasm -pnasm   ..\libavutil\x86\cpuid.asm  ..\libavutil\x86\emms.asm  ..\libavutil\x86\fixed_dsp.asm  ..\libavutil\x86\float_dsp.asm  ..\libavutil\x86\imgutils.asm  ..\libavutil\x86\lls.asm  ..\libavutil\x86\pixelutils.asm" exited with code 1.

**2. Some of the include files required for building are missing. For instance** 

6>..\libavformat\tls_gnutls.c(24): fatal error C1083: Cannot open include file: 'gnutls/gnutls.h': No such file or directory

## Steps to Reproduce

1.  clone the ffmpeg project on windows.
2.  Install yasm as instructed.
3.  In the project run project_get_dependencies.bat
4.   clone the projects manually so that they are all next to ffmpeg.
5.   open ffmpeg/smp/ffmpeg.sln.
6. Select x64 configuration and rebuild all.

## Your Environment
* Version Used:
* Operating System and Version:
Windows 10 64 bit
* Compiler and Version(s):
Visual Studio 2015

## Possible Fix
It is possible that I am missing a configuration or installation step.
If so, I would like know where to find information on that.

**Comment by david-sackstein** [comment]
One of these problems has been resolved. 
I had not installed YASM problem.
Instead of following the instructions at where YASM is downloaded, I ran the install script in the YASM installation pointed to be the readme in SMP/readme.txt.

**Comment by david-sackstein** [comment]
But a problem still remains with finding included headers for some of the projects.
For instance <zlib.h> needs to be replaced with "../../zlib/zlib.h" and there are many others.
Is there are configuration step I am missing?

**Comment by david-sackstein** [comment]
The problem I encountered running project_get_dependencies.bat was caused by there being spaces in the path to the project (or maybe because the path was too long). I moved the project to c:\ShiftMedia and the batch file ran ok.
However, even after running the batch file I got these errors when rebuilding ffmpeg.sln:

`Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'GL/glext.h': No such file or directory	libavdevice	C:\ShiftMedia\FFmpeg\libavdevice\opengl_enc.c	43	
Error	C1083	Cannot open include file: 'mfx/mfxvideo.h': No such file or directory	libavutil	C:\ShiftMedia\FFmpeg\libavutil\hwcontext_qsv.c	22	
Error	C1083	Cannot open include file: 'soxr.h': No such file or directory	libswresample	C:\ShiftMedia\FFmpeg\libswresample\soxr_resample.c	30	
Error	C1083	Cannot open include file: 'xvid.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\libxvid.c	30	
Error	C1083	Cannot open include file: 'x265.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\libx265.c	27	
Error	C1083	Cannot open include file: 'x264.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\libx264.c	36	
Error	C1083	Cannot open include file: 'vpx/vpx_codec.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\libvpx.c	21	
Error	C1083	Cannot open include file: 'vpx/vpx_encoder.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\libvpxenc.c	28	
Error	C1083	Cannot open include file: 'vorbis/vorbisenc.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\libvorbisenc.c	21	
Error	C1083	Cannot open include file: 'vorbis/vorbisenc.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\libvorbisdec.c	21	
Error	C1083	Cannot open include file: 'theora/theoraenc.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\libtheoraenc.c	43	
Error	C1083	Cannot open include file: 'speex/speex.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\libspeexenc.c	84	
Error	C1083	Cannot open include file: 'speex/speex.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\libspeexdec.c	21	
Error	C1083	Cannot open include file: 'opus_defines.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\libopus.c	22	
Error	C1083	Cannot open include file: 'opus.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\libopusenc.c	22	
Error	C1083	Cannot open include file: 'lame/lame.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\libmp3lame.c	27	
Error	C1083	Cannot open include file: 'ilbc.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\libilbc.c	22	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\zmbvenc.c	35	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\zmbv.c	36	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\lclenc.c	50	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\zerocodec.c	19	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\tscc.c	44	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\tiffenc.c	30	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\tiff.c	29	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\tdsc.c	37	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\svq3.c	58	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\screenpresso.c	38	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\rscc.c	39	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\lcldec.c	52	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\mscc.c	31	
Error	C1083	Cannot open include file: 'mfx/mfxvideo.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\qsvenc_mpeg2.c	25	
Error	C1083	Cannot open include file: 'mfx/mfxvideo.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\qsvdec_other.c	27	
Error	C1083	Cannot open include file: 'mfx/mfxvideo.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\qsvenc_hevc.c	25	
Error	C1083	Cannot open include file: 'mfx/mfxvideo.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\qsvenc_h264.c	27	
Error	C1083	Cannot open include file: 'mfx/mfxvideo.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\qsvdec_h2645.c	28	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\g2meet.c	29	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\flashsv2enc.c	47	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\flashsvenc.c	49	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\flashsv.c	38	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\exr.c	38	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\dxa.c	36	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\cscd.c	29	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\pngenc.c	36	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\pngdec.c	37	
Error	C1083	Cannot open include file: 'mfx/mfxvideo.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\qsvenc.c	26	
Error	C1083	Cannot open include file: 'mfx/mfxvideo.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\qsvdec.c	27	
Error	C1083	Cannot open include file: 'mfx/mfxvideo.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\qsv.c	21	
Error	C1083	Cannot open include file: 'xvid.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\libxvid_rc.c	33	
Error	C1083	Cannot open include file: 'iconv.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\utils.c	62	
Error	C1083	Cannot open include file: 'mfx/mfxvideo.h': No such file or directory	libavcodec	c:\shiftmedia\ffmpeg\libavcodec\qsv.h	24	
Error	C1083	Cannot open include file: 'iconv.h': No such file or directory	libavcodec	C:\ShiftMedia\FFmpeg\libavcodec\decode.c	27	
Error	C1083	Cannot open include file: 'gnutls/gnutls.h': No such file or directory	libavformat	C:\ShiftMedia\FFmpeg\libavformat\tls_gnutls.c	24	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavformat	C:\ShiftMedia\FFmpeg\libavformat\rtmpproto.c	48	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavformat	C:\ShiftMedia\FFmpeg\libavformat\http.c	25	
Error	C1083	Cannot open include file: 'gmp.h': No such file or directory	libavformat	c:\shiftmedia\ffmpeg\libavformat\rtmpdh.h	30	
Error	C1083	Cannot open include file: 'gmp.h': No such file or directory	libavformat	c:\shiftmedia\ffmpeg\libavformat\rtmpdh.h	30	
Error	C1083	Cannot open include file: 'libbluray/bluray.h': No such file or directory	libavformat	C:\ShiftMedia\FFmpeg\libavformat\bluray.c	23	
Error	C1083	Cannot open include file: 'libssh/sftp.h': No such file or directory	libavformat	C:\ShiftMedia\FFmpeg\libavformat\libssh.c	23	
Error	C1083	Cannot open include file: 'libmodplug/modplug.h': No such file or directory	libavformat	C:\ShiftMedia\FFmpeg\libavformat\libmodplug.c	26	
Error	C1083	Cannot open include file: 'gme/gme.h': No such file or directory	libavformat	C:\ShiftMedia\FFmpeg\libavformat\libgme.c	24	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavformat	C:\ShiftMedia\FFmpeg\libavformat\swfdec.c	26	
Error	C1083	Cannot open include file: 'bzlib.h': No such file or directory	libavformat	C:\ShiftMedia\FFmpeg\libavformat\matroskadec.c	63	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavformat	C:\ShiftMedia\FFmpeg\libavformat\mov.c	63	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavformat	c:\shiftmedia\ffmpeg\libavformat\swf.h	29	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	libavformat	C:\ShiftMedia\FFmpeg\libavformat\id3v2.c	32	
Error	C1083	Cannot open include file: 'mfx/mfxvideo.h': No such file or directory	libavfilter	C:\ShiftMedia\FFmpeg\libavfilter\vf_scale_qsv.c	24	
Error	C1083	Cannot open include file: 'fontconfig/fontconfig.h': No such file or directory	libavfilter	C:\ShiftMedia\FFmpeg\libavfilter\vf_drawtext.c	43	
Error	C1083	Cannot open include file: 'mfx/mfxvideo.h': No such file or directory	libavfilter	C:\ShiftMedia\FFmpeg\libavfilter\vf_deinterlace_qsv.c	24	
Error	C1083	Cannot open include file: 'ass/ass.h': No such file or directory	libavfilter	C:\ShiftMedia\FFmpeg\libavfilter\vf_subtitles.c	30	
Error	C1083	Cannot open include file: 'cdio/paranoia/cdda.h': No such file or directory	libavdevice	C:\ShiftMedia\FFmpeg\libavdevice\libcdio.c	32	
Error	C1083	Cannot open include file: 'SDL.h': No such file or directory	libavdevice	C:\ShiftMedia\FFmpeg\libavdevice\sdl2.c	26	`

**Comment by Sibras** [comment]
Ill look into why the project_get_dependencies.bat file may not work, however any additional information you can give me may help.

As for the errors you are getting, these are because the dependencies have not been built and so they can not be found. You should instead use the ffmpeg_deps.sln solution as this includes links to all the downloaded repositories and will automatically build them as needed. So the only thing you have to manually do is get the glext headers as per the readme in the SMP folder.

Also in case you didnt know I will point out that pre-built VS 2015 static and dynamic release builds can be download from the release section of the repo so you only need to compile yourself if you want debug builds or to edit the code.

**Comment by david-sackstein** [comment]
Problem solved.
The mxf folder had been given a different name by the clone.
I renamed it to mxf and all dependencies were found.
Thank you

**Comment by Sibras** [comment]
I just pushed an update that should hopefully resolve any issues with project_get_dependencies.bat in the future.
This script can also be used to update any existing download dependencies to the latest versions (if any new ones exist) so let me know if you have any issues with it in the future.

**Comment by tomachristian** [comment]
@Sibras I still have the problem with `mfx/mfxvideo.h` not being found on the first clean build, after a second build the error goes away. This is with the latest version on `master`.

```
..\libavutil\hwcontext_qsv.c(22): fatal error C1083: Cannot open include file: 'mfx/mfxvideo.h': No such file or directory [C:\Workspaces\FFmpeg\src\ffmpeg\SMP\libavutil.vcxproj]
```

**Comment by Sibras** [comment]
This is a simple build order fix for the ffmpeg_deps.sln file. Its fixed now in latest master.
